services:
  seguridad-app:
    build:
      context: .
      dockerfile: ./microservicio_seguridad/Dockerfile
    container_name: seguridad-app
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./microservicio_seguridad:/var/www/html/microservicio_seguridad
    depends_on:
      seguridad-db:
        condition: service_healthy
    networks:
      - app_net

  seguridad-db:
    image: mysql:8
    container_name: seguridad-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: seguridad_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_seguridad_data:/var/lib/mysql
    networks:
      - app_net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5

  tareas-app:
    build:
      context: .
      dockerfile: ./microservicio_tareas/Dockerfile
    container_name: tareas-app
    restart: always
    ports:
      - "8001:8000"
    volumes:
      - ./microservicio_tareas:/var/www/html/microservicio_tareas
    depends_on:
      tareas-db:
        condition: service_healthy
    networks:
      - app_net

  tareas-db:
    image: mysql:8
    container_name: tareas-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tareas_db
      MYSQL_USER: user_tareas
      MYSQL_PASSWORD: pass_tareas
    ports:
      - "3308:3306"
    volumes:
      - mysql_tareas_data:/var/lib/mysql
    networks:
      - app_net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5

  foro-app:
    build:
      context: .
      dockerfile: ./microservicio_foro/Dockerfile
    container_name: foro-app
    ports:
      - "9000:9000"
    volumes:
      - ./microservicio_foro:/var/www/html/microservicio_foro
    environment:
      DB_HOST: foro-db
      DB_PORT: 3306
      DB_NAME: foro_db
      DB_USER: foro_user
      DB_PASSWORD: foro_pass
      SECURITY_SERVICE_URL: http://seguridad-app:8000/api
    depends_on:
      foro-db:
        condition: service_healthy
    networks:
      - app_net

  foro-db:
    image: mysql:8.0
    container_name: foro-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: foro_db
      MYSQL_USER: foro_user
      MYSQL_PASSWORD: foro_pass
    ports:
      - "3309:3306"
    volumes:
      - foro_mysql_data:/var/lib/mysql
    networks:
      - app_net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5

  reportes-app:
    build:
      context: .
      dockerfile: ./microservicio_reportes/Dockerfile
    container_name: reportes-app
    depends_on:
      tareas-db:
        condition: service_healthy
      reportes-mongo:
        condition: service_started
    environment:
      MYSQL_HOST: tareas-db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: tareas_db
      MYSQL_USER: user_tareas
      MYSQL_PASSWORD: pass_tareas
      MONGO_HOST: reportes-mongo
    ports:
      - "5000:5000"
    volumes:
      - ./microservicio_reportes:/var/www/html/microservicio_reportes
    networks:
      - app_net

  reportes-mongo:
    image: mongo:6
    container_name: reportes-mongo
    ports:
      - "27017:27017"
    volumes:
      - reportes-mongo-data:/data/db
    networks:
      - app_net

networks:
  app_net:
    driver: bridge

volumes:
  mysql_tareas_data:
  mysql_seguridad_data:
  foro_mysql_data:
  reportes-mongo-data:
