services:
  db_foro:
    image: mysql:8.0
    container_name: db_foro
    restart: always
    environment:
      MYSQL_DATABASE: foro
      MYSQL_USER: foro_user
      MYSQL_PASSWORD: foro_pass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3307:3306"
    volumes:
      - foro_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  web_foro:
    build: .
    container_name: foro_django
    restart: always
    command: python manage.py runserver 0.0.0.0:9000
    volumes:
      - .:/app
    ports:
      - "9000:9000"
    depends_on:
      - db_foro
    environment:
      # Variables de conexi√≥n con la base de datos
      DB_NAME: foro
      DB_USER: foro_user
      DB_PASSWORD: foro_pass
      DB_HOST: db_foro
      DB_PORT: 3306

volumes:
  foro_data:
